# Generated by Django 4.1.3 on 2022-11-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('telephone1', models.IntegerField(max_length=7)),
                ('telephone2', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
